# Load general dependencies
load("//:deps.bzl", "deps")

deps()

# Define dev dependencies directly in the WORKSPACE file.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "6e78f0e57de26801f6f564fa7c4a48dc8b36873e416257a92bbb0937eeac8446",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.2/bazel-skylib-1.8.2.tar.gz"],
)

load("@librarian//:librarian.bzl", "fetch_book")

fetch_book(
    name = "hamlet",
    edition = "2005.1",
)
