# Load general dependencies
load("//:deps.bzl", "deps")

deps()

# Define dev dependencies directly in the WORKSPACE file.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "3b5b49006181f5f8ff626ef8ddceaa95e9bb8ad294f7b5d7b11ea9f7ddaf8c59",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/1.9.0/bazel-skylib-1.9.0.tar.gz"],
)

load("@librarian//:librarian.bzl", "fetch_book")

fetch_book(
    name = "hamlet",
    edition = "2005.1",
)
