http_archive(
    name = "rules_cc",
    sha256 = "207ea073dd20a705f9e8bc5ac02f5203e9621fc672774bb1a0935aefab7aebfa",
    strip_prefix = "rules_cc-0.2.8",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.2.8/rules_cc-0.2.8.tar.gz"],
)
