load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "librarian",
    path = "../utils/librarian",
)

load("@librarian//:librarian.bzl", "fetch_book")

fetch_book(
    name = "the_great_gatsby",
    edition = "1995.12",
)

fetch_book(
    name = "hamlet",
    edition = "1800.1",
)

local_repository(
    name = "lib_a",
    path = "./lib_a",
)

load("@lib_a//:deps.bzl", "deps")

deps()

http_archive(
    name = "bazel_skylib",
    sha256 = "51b5105a760b353773f904d2bbc5e664d0987fbaf22265164de65d43e910d8ac",
    urls = ["https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.1/bazel-skylib-1.8.1.tar.gz"],
)
